application: carsonblogalog
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /
  script: main.py
  
- url: /index\.html
  script: main.py
  
- url: /post
  script: post.py
  login: admin
  
- url: /postpost
  script: post.py
  login: admin
  
- url: /edit
  script: edit.py
  login: admin
  
- url: /edit/(.*)
  script: edit.py
  login: admin
  
- url: /update
  script: edit.py
  login: admin
  
- url: /.*
  script: oops.py
  
