application: carsonblogalog
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /
  script: main.py
  
- url: /index\.html
  script: main.py
  
- url: /.*
  script: oops.py
  
